<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260408194415 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE app_action_catalog (id INT AUTO_INCREMENT NOT NULL, code VARCHAR(50) NOT NULL, name VARCHAR(100) NOT NULL, UNIQUE INDEX UNIQ_1E74285877153098 (code), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4 COMMENT = \'Catálogo de acciones disponibles en el sistema (crear, leer, actualizar, eliminar, exportar)\' ');
        $this->addSql('CREATE TABLE app_functionality (id INT AUTO_INCREMENT NOT NULL, code VARCHAR(50) NOT NULL, name VARCHAR(100) NOT NULL, display_order INT NOT NULL, active TINYINT NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, app_module_id INT NOT NULL, UNIQUE INDEX UNIQ_624162E877153098 (code), INDEX IDX_624162E87ADEAA4 (app_module_id), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4 COMMENT = \'Funcionalidades específicas dentro de un módulo sobre las cuales se asignan permisos de acción por rol\' ');
        $this->addSql('CREATE TABLE app_module (id INT AUTO_INCREMENT NOT NULL, code VARCHAR(50) NOT NULL, name VARCHAR(100) NOT NULL, icon VARCHAR(50) NOT NULL, display_order INT NOT NULL, active TINYINT NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, UNIQUE INDEX UNIQ_E9274BA877153098 (code), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4 COMMENT = \'Módulos principales del sistema (Catálogos, Seguridad, Ventas, etc.) que agrupan funcionalidades\' ');
        $this->addSql('CREATE TABLE app_role (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(100) NOT NULL, description VARCHAR(255) DEFAULT NULL, active TINYINT NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, UNIQUE INDEX UNIQ_5247AFCA5E237E06 (name), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4 COMMENT = \'Roles del sistema que agrupan permisos de acceso a módulos y acciones sobre funcionalidades\' ');
        $this->addSql('CREATE TABLE app_role_action_permission (id INT AUTO_INCREMENT NOT NULL, allowed TINYINT NOT NULL, role_id INT NOT NULL, app_function_id INT NOT NULL, action_id INT NOT NULL, INDEX IDX_EE188C05D60322AC (role_id), INDEX IDX_EE188C053EE1AEBD (app_function_id), INDEX IDX_EE188C059D32F035 (action_id), UNIQUE INDEX unique_role_function_action (role_id, app_function_id, action_id), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4 COMMENT = \'Permisos granulares que definen qué acciones (crear, leer, actualizar, eliminar, exportar) puede realizar un rol sobre cada funcionalidad\' ');
        $this->addSql('CREATE TABLE app_role_module_permission (id INT AUTO_INCREMENT NOT NULL, can_access TINYINT NOT NULL, role_id INT NOT NULL, app_module_id INT NOT NULL, INDEX IDX_185FCD52D60322AC (role_id), INDEX IDX_185FCD527ADEAA4 (app_module_id), UNIQUE INDEX unique_role_module (role_id, app_module_id), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4 COMMENT = \'Permisos de acceso de un rol a un módulo del sistema\' ');
        $this->addSql('CREATE TABLE app_user (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(100) NOT NULL, last_name VARCHAR(100) DEFAULT NULL, phone VARCHAR(20) DEFAULT NULL, email VARCHAR(180) NOT NULL, roles JSON NOT NULL, password VARCHAR(255) NOT NULL, acronym VARCHAR(20) DEFAULT NULL, active TINYINT NOT NULL, is_mobile_allowed TINYINT NOT NULL, image VARCHAR(255) DEFAULT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, role_id INT DEFAULT NULL, company_id INT DEFAULT NULL, branch_id INT DEFAULT NULL, department_id INT DEFAULT NULL, UNIQUE INDEX UNIQ_88BDF3E9444F97DD (phone), UNIQUE INDEX UNIQ_88BDF3E9E7927C74 (email), INDEX IDX_88BDF3E9D60322AC (role_id), INDEX IDX_88BDF3E9979B1AD6 (company_id), INDEX IDX_88BDF3E9DCD6CC49 (branch_id), INDEX IDX_88BDF3E9AE80F5DF (department_id), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4 COMMENT = \'Usuarios del sistema con credenciales de acceso, rol asignado y estado activo/inactivo\' ');
        $this->addSql('CREATE TABLE app_user_session (id INT AUTO_INCREMENT NOT NULL, token LONGTEXT NOT NULL, ip_address VARCHAR(45) DEFAULT NULL, user_agent VARCHAR(500) DEFAULT NULL, login_at DATETIME NOT NULL, logout_at DATETIME DEFAULT NULL, last_activity_at DATETIME NOT NULL, active TINYINT NOT NULL, user_id INT NOT NULL, INDEX IDX_4AC7D15FA76ED395 (user_id), INDEX idx_session_active (active), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4 COMMENT = \'Registro de sesiones de usuario, rastreando login, logout, actividad y expiración por inactividad\' ');
        $this->addSql('CREATE TABLE branch (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(150) NOT NULL, abbreviations VARCHAR(20) DEFAULT NULL, address JSON DEFAULT NULL, phone VARCHAR(20) DEFAULT NULL, schedule LONGTEXT DEFAULT NULL, image LONGTEXT DEFAULT NULL, active TINYINT NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, company_id INT NOT NULL, INDEX IDX_BB861B1F979B1AD6 (company_id), UNIQUE INDEX uniq_branch_company_name (company_id, name), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4');
        $this->addSql('CREATE TABLE brand (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(100) NOT NULL, acronym VARCHAR(10) DEFAULT NULL, description VARCHAR(255) DEFAULT NULL, active TINYINT NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, UNIQUE INDEX UNIQ_1C52F9585E237E06 (name), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4');
        $this->addSql('CREATE TABLE category (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(100) NOT NULL, acronym VARCHAR(10) DEFAULT NULL, description VARCHAR(255) DEFAULT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, UNIQUE INDEX UNIQ_64C19C15E237E06 (name), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4');
        $this->addSql('CREATE TABLE company (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(150) NOT NULL, trade_name VARCHAR(150) DEFAULT NULL, legal_name VARCHAR(150) DEFAULT NULL, acronym VARCHAR(20) DEFAULT NULL, tagline VARCHAR(255) DEFAULT NULL, description LONGTEXT DEFAULT NULL, tax_id VARCHAR(20) DEFAULT NULL, address JSON DEFAULT NULL, phone VARCHAR(20) DEFAULT NULL, email VARCHAR(255) DEFAULT NULL, url VARCHAR(255) DEFAULT NULL, active TINYINT NOT NULL, image VARCHAR(255) DEFAULT NULL, social_networks JSON DEFAULT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, UNIQUE INDEX UNIQ_4FBF094F5E237E06 (name), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4');
        $this->addSql('CREATE TABLE customer (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(255) NOT NULL, email VARCHAR(255) DEFAULT NULL, phone VARCHAR(20) DEFAULT NULL, address LONGTEXT DEFAULT NULL, tax_id VARCHAR(50) DEFAULT NULL, active TINYINT NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, INDEX idx_customer_name (name), INDEX idx_customer_email (email), INDEX idx_customer_phone (phone), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4');
        $this->addSql('CREATE TABLE department (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(150) NOT NULL, acronym VARCHAR(20) DEFAULT NULL, description VARCHAR(255) DEFAULT NULL, active TINYINT NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, company_id INT NOT NULL, INDEX IDX_CD1DE18A979B1AD6 (company_id), UNIQUE INDEX uniq_department_company_name (company_id, name), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4');
        $this->addSql('CREATE TABLE fabric_type (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(100) NOT NULL, acronym VARCHAR(10) DEFAULT NULL, description VARCHAR(255) DEFAULT NULL, active TINYINT NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, UNIQUE INDEX UNIQ_F6B419FB5E237E06 (name), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4');
        $this->addSql('CREATE TABLE garment_type (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(100) NOT NULL, acronym VARCHAR(10) DEFAULT NULL, description VARCHAR(255) DEFAULT NULL, active TINYINT NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, UNIQUE INDEX UNIQ_2D3D3FD95E237E06 (name), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4');
        $this->addSql('CREATE TABLE gender_catalog (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(100) NOT NULL, acronym VARCHAR(10) DEFAULT NULL, description VARCHAR(255) DEFAULT NULL, active TINYINT NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, UNIQUE INDEX UNIQ_E9C447FB5E237E06 (name), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4');
        $this->addSql('CREATE TABLE inventory_count (id INT AUTO_INCREMENT NOT NULL, folio VARCHAR(30) NOT NULL, status VARCHAR(20) NOT NULL, count_date DATE NOT NULL, notes LONGTEXT DEFAULT NULL, total_items INT NOT NULL, discrepancies INT NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, company_id INT NOT NULL, warehouse_id INT NOT NULL, user_id INT NOT NULL, UNIQUE INDEX UNIQ_5945EF629BEA0CC6 (folio), INDEX IDX_5945EF62979B1AD6 (company_id), INDEX IDX_5945EF625080ECDE (warehouse_id), INDEX IDX_5945EF62A76ED395 (user_id), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4');
        $this->addSql('CREATE TABLE inventory_count_detail (id INT AUTO_INCREMENT NOT NULL, system_qty INT NOT NULL, counted_qty INT DEFAULT NULL, difference INT DEFAULT NULL, status VARCHAR(20) NOT NULL, notes LONGTEXT DEFAULT NULL, counted_at DATETIME DEFAULT NULL, first_counted_qty INT DEFAULT NULL, first_difference INT DEFAULT NULL, first_counted_at DATETIME DEFAULT NULL, inventory_count_id INT NOT NULL, paca_id INT NOT NULL, INDEX IDX_A18FB9AF242801B (inventory_count_id), INDEX IDX_A18FB9A76A45273 (paca_id), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4');
        $this->addSql('CREATE TABLE inventory_movement (id INT AUTO_INCREMENT NOT NULL, movement_type VARCHAR(3) NOT NULL, reference_type VARCHAR(50) DEFAULT NULL, reference_id INT DEFAULT NULL, qty_in INT NOT NULL, qty_out INT NOT NULL, balance_after INT NOT NULL, unit_cost NUMERIC(10, 2) DEFAULT NULL, notes LONGTEXT DEFAULT NULL, created_at DATETIME NOT NULL, company_id INT NOT NULL, paca_id INT NOT NULL, warehouse_id INT NOT NULL, warehouse_bin_id INT DEFAULT NULL, reason_id INT NOT NULL, user_id INT NOT NULL, paca_unit_id INT DEFAULT NULL, INDEX IDX_40972F66979B1AD6 (company_id), INDEX IDX_40972F66C77159AD (warehouse_bin_id), INDEX IDX_40972F6659BB1592 (reason_id), INDEX IDX_40972F66A76ED395 (user_id), INDEX idx_movement_paca (paca_id), INDEX idx_movement_warehouse (warehouse_id), INDEX idx_movement_date (created_at), INDEX idx_movement_reference (reference_type, reference_id), INDEX idx_movement_paca_unit (paca_unit_id), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4');
        $this->addSql('CREATE TABLE inventory_reason (id INT AUTO_INCREMENT NOT NULL, code VARCHAR(30) NOT NULL, name VARCHAR(100) NOT NULL, direction VARCHAR(3) NOT NULL, requires_reference TINYINT NOT NULL, is_active TINYINT NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, UNIQUE INDEX UNIQ_3B6414A777153098 (code), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4');
        $this->addSql('CREATE TABLE inventory_snapshot (id INT AUTO_INCREMENT NOT NULL, snapshot_date DATE NOT NULL, total_pacas INT NOT NULL, total_stock INT NOT NULL, total_value_purchase NUMERIC(14, 2) NOT NULL, total_value_selling NUMERIC(14, 2) NOT NULL, movements_in INT NOT NULL, movements_out INT NOT NULL, low_stock_count INT NOT NULL, out_of_stock_count INT NOT NULL, data_json JSON DEFAULT NULL, created_at DATETIME NOT NULL, company_id INT NOT NULL, warehouse_id INT NOT NULL, INDEX IDX_9807AFA4979B1AD6 (company_id), INDEX IDX_9807AFA45080ECDE (warehouse_id), INDEX idx_snapshot_composite (company_id, warehouse_id, snapshot_date), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4');
        $this->addSql('CREATE TABLE label_catalog (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(100) NOT NULL, acronym VARCHAR(10) DEFAULT NULL, description VARCHAR(255) DEFAULT NULL, active TINYINT NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, UNIQUE INDEX UNIQ_A7AD9B6E5E237E06 (name), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4');
        $this->addSql('CREATE TABLE paca (id INT AUTO_INCREMENT NOT NULL, code VARCHAR(50) NOT NULL, name VARCHAR(255) NOT NULL, description LONGTEXT DEFAULT NULL, purchase_price NUMERIC(10, 2) NOT NULL, selling_price NUMERIC(10, 2) NOT NULL, cached_stock INT NOT NULL, piece_count INT DEFAULT NULL, weight NUMERIC(8, 2) DEFAULT NULL, active TINYINT NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, brand_id INT DEFAULT NULL, label_id INT DEFAULT NULL, quality_grade_id INT DEFAULT NULL, season_id INT DEFAULT NULL, gender_id INT DEFAULT NULL, garment_type_id INT DEFAULT NULL, fabric_type_id INT DEFAULT NULL, size_profile_id INT DEFAULT NULL, supplier_id INT DEFAULT NULL, UNIQUE INDEX UNIQ_770BB73D77153098 (code), INDEX IDX_770BB73D44F5D008 (brand_id), INDEX IDX_770BB73D33B92F39 (label_id), INDEX IDX_770BB73DEA7929DC (quality_grade_id), INDEX IDX_770BB73D4EC001D1 (season_id), INDEX IDX_770BB73D708A0E0 (gender_id), INDEX IDX_770BB73DE4AFAD8F (garment_type_id), INDEX IDX_770BB73D88DC877A (fabric_type_id), INDEX IDX_770BB73D161591CD (size_profile_id), INDEX IDX_770BB73D2ADD6D8C (supplier_id), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4');
        $this->addSql('CREATE TABLE paca_import_log (id INT AUTO_INCREMENT NOT NULL, filename VARCHAR(255) NOT NULL, original_filename VARCHAR(255) NOT NULL, total_rows INT NOT NULL, processed_rows INT NOT NULL, created_count INT NOT NULL, updated_count INT NOT NULL, error_count INT NOT NULL, errors JSON NOT NULL, status VARCHAR(20) NOT NULL, created_at DATETIME NOT NULL, completed_at DATETIME DEFAULT NULL, user_id INT NOT NULL, INDEX IDX_D30DA832A76ED395 (user_id), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4');
        $this->addSql('CREATE TABLE paca_unit (id INT AUTO_INCREMENT NOT NULL, serial VARCHAR(30) NOT NULL, status VARCHAR(20) NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, paca_id INT NOT NULL, warehouse_id INT NOT NULL, warehouse_bin_id INT DEFAULT NULL, sales_order_id INT DEFAULT NULL, sales_order_item_id INT DEFAULT NULL, purchase_order_id INT DEFAULT NULL, UNIQUE INDEX UNIQ_34A1768CD374C9DC (serial), INDEX IDX_34A1768C76A45273 (paca_id), INDEX IDX_34A1768CC77159AD (warehouse_bin_id), INDEX IDX_34A1768C21338DA6 (sales_order_item_id), INDEX IDX_34A1768CA45D7E6A (purchase_order_id), INDEX idx_paca_unit_paca_status (paca_id, status), INDEX idx_paca_unit_warehouse (warehouse_id), INDEX idx_paca_unit_status (status), INDEX idx_paca_unit_so (sales_order_id), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4');
        $this->addSql('CREATE TABLE payment (id INT AUTO_INCREMENT NOT NULL, amount NUMERIC(10, 2) NOT NULL, method VARCHAR(20) NOT NULL, status VARCHAR(20) NOT NULL, transaction_id VARCHAR(100) DEFAULT NULL, notes LONGTEXT DEFAULT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, sale_id INT NOT NULL, INDEX IDX_6D28840D4A7E4868 (sale_id), INDEX idx_payment_status (status), INDEX idx_payment_method (method), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4');
        $this->addSql('CREATE TABLE product (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(255) NOT NULL, description LONGTEXT DEFAULT NULL, price NUMERIC(10, 2) NOT NULL, stock INT NOT NULL, barcode VARCHAR(50) DEFAULT NULL, active TINYINT NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, category_id INT DEFAULT NULL, INDEX IDX_D34A04AD12469DE2 (category_id), INDEX idx_product_name (name), INDEX idx_product_price (price), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4');
        $this->addSql('CREATE TABLE purchase_order (id INT AUTO_INCREMENT NOT NULL, folio VARCHAR(30) NOT NULL, status VARCHAR(20) NOT NULL, order_date DATE NOT NULL, expected_date DATE DEFAULT NULL, received_date DATE DEFAULT NULL, subtotal NUMERIC(14, 2) NOT NULL, tax NUMERIC(14, 2) NOT NULL, discount NUMERIC(14, 2) NOT NULL, total NUMERIC(14, 2) NOT NULL, notes LONGTEXT DEFAULT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, company_id INT NOT NULL, supplier_id INT NOT NULL, user_id INT NOT NULL, UNIQUE INDEX UNIQ_21E210B29BEA0CC6 (folio), INDEX IDX_21E210B2A76ED395 (user_id), INDEX idx_po_company (company_id), INDEX idx_po_supplier (supplier_id), INDEX idx_po_folio (folio), INDEX idx_po_status (status), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4');
        $this->addSql('CREATE TABLE purchase_order_item (id INT AUTO_INCREMENT NOT NULL, description VARCHAR(255) NOT NULL, expected_qty INT NOT NULL, received_qty INT NOT NULL, unit_price NUMERIC(10, 2) NOT NULL, total_price NUMERIC(14, 2) NOT NULL, status VARCHAR(20) NOT NULL, notes LONGTEXT DEFAULT NULL, purchase_order_id INT NOT NULL, label_id INT DEFAULT NULL, paca_id INT DEFAULT NULL, INDEX IDX_5ED948C3A45D7E6A (purchase_order_id), INDEX IDX_5ED948C333B92F39 (label_id), INDEX IDX_5ED948C376A45273 (paca_id), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4');
        $this->addSql('CREATE TABLE quality_grade (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(100) NOT NULL, acronym VARCHAR(10) DEFAULT NULL, description VARCHAR(255) DEFAULT NULL, active TINYINT NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, UNIQUE INDEX UNIQ_4DF466075E237E06 (name), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4');
        $this->addSql('CREATE TABLE sale (id INT AUTO_INCREMENT NOT NULL, subtotal NUMERIC(10, 2) NOT NULL, tax NUMERIC(10, 2) NOT NULL, discount NUMERIC(10, 2) NOT NULL, total NUMERIC(10, 2) NOT NULL, status VARCHAR(20) NOT NULL, payment_method VARCHAR(20) NOT NULL, notes LONGTEXT DEFAULT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, customer_id INT DEFAULT NULL, INDEX IDX_E54BC0059395C3F3 (customer_id), INDEX idx_sale_status (status), INDEX idx_sale_payment_method (payment_method), INDEX idx_sale_created_at (created_at), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4');
        $this->addSql('CREATE TABLE sale_item (id INT AUTO_INCREMENT NOT NULL, quantity INT NOT NULL, unit_price NUMERIC(10, 2) NOT NULL, total_price NUMERIC(10, 2) NOT NULL, tax_amount NUMERIC(10, 2) NOT NULL, discount_amount NUMERIC(10, 2) NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, sale_id INT NOT NULL, product_id INT NOT NULL, INDEX IDX_A35551FB4A7E4868 (sale_id), INDEX IDX_A35551FB4584665A (product_id), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4');
        $this->addSql('CREATE TABLE sales_order (id INT AUTO_INCREMENT NOT NULL, customer_address LONGTEXT DEFAULT NULL, folio VARCHAR(30) NOT NULL, channel VARCHAR(20) NOT NULL, order_type VARCHAR(20) NOT NULL, status VARCHAR(20) NOT NULL, payment_status VARCHAR(20) NOT NULL, delivery_status VARCHAR(20) NOT NULL, subtotal NUMERIC(14, 2) NOT NULL, tax NUMERIC(14, 2) NOT NULL, discount NUMERIC(14, 2) NOT NULL, shipping_cost NUMERIC(10, 2) NOT NULL, total NUMERIC(14, 2) NOT NULL, notes LONGTEXT DEFAULT NULL, source_whatsapp VARCHAR(30) DEFAULT NULL, estimated_delivery DATE DEFAULT NULL, delivered_at DATETIME DEFAULT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, company_id INT NOT NULL, branch_id INT DEFAULT NULL, customer_id INT NOT NULL, seller_id INT DEFAULT NULL, user_id INT NOT NULL, UNIQUE INDEX UNIQ_36D222E9BEA0CC6 (folio), INDEX IDX_36D222EDCD6CC49 (branch_id), INDEX IDX_36D222E8DE820D9 (seller_id), INDEX IDX_36D222EA76ED395 (user_id), INDEX idx_so_company (company_id), INDEX idx_so_customer (customer_id), INDEX idx_so_folio (folio), INDEX idx_so_status (status), INDEX idx_so_channel (channel), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4');
        $this->addSql('CREATE TABLE sales_order_item (id INT AUTO_INCREMENT NOT NULL, quantity INT NOT NULL, unit_price NUMERIC(10, 2) NOT NULL, discount NUMERIC(10, 2) NOT NULL, total_price NUMERIC(14, 2) NOT NULL, commission_rule_id INT DEFAULT NULL, notes LONGTEXT DEFAULT NULL, sales_order_id INT NOT NULL, paca_id INT NOT NULL, INDEX IDX_5DD6A865C023F51C (sales_order_id), INDEX IDX_5DD6A86576A45273 (paca_id), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4');
        $this->addSql('CREATE TABLE sales_order_status_history (id INT AUTO_INCREMENT NOT NULL, from_status VARCHAR(30) DEFAULT NULL, to_status VARCHAR(30) NOT NULL, notes LONGTEXT DEFAULT NULL, created_at DATETIME NOT NULL, sales_order_id INT NOT NULL, user_id INT NOT NULL, INDEX IDX_84EEA80FC023F51C (sales_order_id), INDEX IDX_84EEA80FA76ED395 (user_id), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4');
        $this->addSql('CREATE TABLE season_catalog (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(100) NOT NULL, acronym VARCHAR(10) DEFAULT NULL, description VARCHAR(255) DEFAULT NULL, active TINYINT NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, UNIQUE INDEX UNIQ_3E559B195E237E06 (name), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4');
        $this->addSql('CREATE TABLE shipment_order (id INT AUTO_INCREMENT NOT NULL, folio VARCHAR(30) NOT NULL, tracking_number VARCHAR(100) DEFAULT NULL, status VARCHAR(20) NOT NULL, carrier VARCHAR(100) DEFAULT NULL, notes LONGTEXT DEFAULT NULL, shipped_at DATETIME DEFAULT NULL, delivered_at DATETIME DEFAULT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, sales_order_id INT NOT NULL, warehouse_id INT NOT NULL, created_by_id INT NOT NULL, UNIQUE INDEX UNIQ_79E4313D9BEA0CC6 (folio), INDEX IDX_79E4313DB03A8386 (created_by_id), INDEX idx_sho_sales_order (sales_order_id), INDEX idx_sho_status (status), INDEX idx_sho_folio (folio), INDEX idx_sho_warehouse (warehouse_id), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4');
        $this->addSql('CREATE TABLE shipment_order_item (id INT AUTO_INCREMENT NOT NULL, scanned_at DATETIME NOT NULL, shipment_order_id INT NOT NULL, paca_unit_id INT NOT NULL, scanned_by_id INT NOT NULL, INDEX IDX_30E0C35EBBC642F (scanned_by_id), INDEX idx_shoi_shipment_order (shipment_order_id), INDEX idx_shoi_paca_unit (paca_unit_id), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4');
        $this->addSql('CREATE TABLE size_profile (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(100) NOT NULL, acronym VARCHAR(10) DEFAULT NULL, description VARCHAR(255) DEFAULT NULL, active TINYINT NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, UNIQUE INDEX UNIQ_643A78775E237E06 (name), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4');
        $this->addSql('CREATE TABLE supplier (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(150) NOT NULL, contacts JSON DEFAULT NULL, address LONGTEXT DEFAULT NULL, country VARCHAR(50) DEFAULT NULL, tax_id VARCHAR(20) DEFAULT NULL, active TINYINT NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, UNIQUE INDEX UNIQ_9B2A6C7E5E237E06 (name), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4');
        $this->addSql('CREATE TABLE supplier_label (supplier_id INT NOT NULL, label_catalog_id INT NOT NULL, INDEX IDX_D7BC52C22ADD6D8C (supplier_id), INDEX IDX_D7BC52C21EDAAF39 (label_catalog_id), PRIMARY KEY (supplier_id, label_catalog_id)) DEFAULT CHARACTER SET utf8mb4');
        $this->addSql('CREATE TABLE supplier_brand (id INT AUTO_INCREMENT NOT NULL, active TINYINT NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, supplier_id INT NOT NULL, brand_id INT NOT NULL, INDEX IDX_C549FB722ADD6D8C (supplier_id), INDEX IDX_C549FB7244F5D008 (brand_id), UNIQUE INDEX unique_supplier_brand (supplier_id, brand_id), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4');
        $this->addSql('CREATE TABLE tag (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(100) NOT NULL, color VARCHAR(50) DEFAULT NULL, description VARCHAR(255) DEFAULT NULL, active TINYINT NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, UNIQUE INDEX UNIQ_389B7835E237E06 (name), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4');
        $this->addSql('CREATE TABLE warehouse (id INT AUTO_INCREMENT NOT NULL, code VARCHAR(20) NOT NULL, name VARCHAR(100) NOT NULL, address LONGTEXT DEFAULT NULL, monthly_cost NUMERIC(14, 2) DEFAULT NULL, is_external TINYINT NOT NULL, is_active TINYINT NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, company_id INT NOT NULL, warehouse_type_id INT NOT NULL, UNIQUE INDEX UNIQ_ECB38BFC77153098 (code), INDEX IDX_ECB38BFCE2AB99E6 (warehouse_type_id), INDEX idx_warehouse_company (company_id), INDEX idx_warehouse_code (code), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4');
        $this->addSql('CREATE TABLE warehouse_bin (id INT AUTO_INCREMENT NOT NULL, code VARCHAR(30) NOT NULL, name VARCHAR(100) NOT NULL, zone VARCHAR(50) DEFAULT NULL, bin_type VARCHAR(30) DEFAULT NULL, capacity INT DEFAULT NULL, is_active TINYINT NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, warehouse_id INT NOT NULL, INDEX idx_bin_warehouse (warehouse_id), INDEX idx_bin_code (code), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4');
        $this->addSql('CREATE TABLE warehouse_type (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(100) NOT NULL, description VARCHAR(255) DEFAULT NULL, is_active TINYINT NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, UNIQUE INDEX UNIQ_53B457FD5E237E06 (name), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4');
        $this->addSql('ALTER TABLE app_functionality ADD CONSTRAINT FK_624162E87ADEAA4 FOREIGN KEY (app_module_id) REFERENCES app_module (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE app_role_action_permission ADD CONSTRAINT FK_EE188C05D60322AC FOREIGN KEY (role_id) REFERENCES app_role (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE app_role_action_permission ADD CONSTRAINT FK_EE188C053EE1AEBD FOREIGN KEY (app_function_id) REFERENCES app_functionality (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE app_role_action_permission ADD CONSTRAINT FK_EE188C059D32F035 FOREIGN KEY (action_id) REFERENCES app_action_catalog (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE app_role_module_permission ADD CONSTRAINT FK_185FCD52D60322AC FOREIGN KEY (role_id) REFERENCES app_role (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE app_role_module_permission ADD CONSTRAINT FK_185FCD527ADEAA4 FOREIGN KEY (app_module_id) REFERENCES app_module (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE app_user ADD CONSTRAINT FK_88BDF3E9D60322AC FOREIGN KEY (role_id) REFERENCES app_role (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE app_user ADD CONSTRAINT FK_88BDF3E9979B1AD6 FOREIGN KEY (company_id) REFERENCES company (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE app_user ADD CONSTRAINT FK_88BDF3E9DCD6CC49 FOREIGN KEY (branch_id) REFERENCES branch (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE app_user ADD CONSTRAINT FK_88BDF3E9AE80F5DF FOREIGN KEY (department_id) REFERENCES department (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE app_user_session ADD CONSTRAINT FK_4AC7D15FA76ED395 FOREIGN KEY (user_id) REFERENCES app_user (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE branch ADD CONSTRAINT FK_BB861B1F979B1AD6 FOREIGN KEY (company_id) REFERENCES company (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE department ADD CONSTRAINT FK_CD1DE18A979B1AD6 FOREIGN KEY (company_id) REFERENCES company (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE inventory_count ADD CONSTRAINT FK_5945EF62979B1AD6 FOREIGN KEY (company_id) REFERENCES company (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE inventory_count ADD CONSTRAINT FK_5945EF625080ECDE FOREIGN KEY (warehouse_id) REFERENCES warehouse (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE inventory_count ADD CONSTRAINT FK_5945EF62A76ED395 FOREIGN KEY (user_id) REFERENCES app_user (id) ON DELETE RESTRICT');
        $this->addSql('ALTER TABLE inventory_count_detail ADD CONSTRAINT FK_A18FB9AF242801B FOREIGN KEY (inventory_count_id) REFERENCES inventory_count (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE inventory_count_detail ADD CONSTRAINT FK_A18FB9A76A45273 FOREIGN KEY (paca_id) REFERENCES paca (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE inventory_movement ADD CONSTRAINT FK_40972F66979B1AD6 FOREIGN KEY (company_id) REFERENCES company (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE inventory_movement ADD CONSTRAINT FK_40972F6676A45273 FOREIGN KEY (paca_id) REFERENCES paca (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE inventory_movement ADD CONSTRAINT FK_40972F665080ECDE FOREIGN KEY (warehouse_id) REFERENCES warehouse (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE inventory_movement ADD CONSTRAINT FK_40972F66C77159AD FOREIGN KEY (warehouse_bin_id) REFERENCES warehouse_bin (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE inventory_movement ADD CONSTRAINT FK_40972F6659BB1592 FOREIGN KEY (reason_id) REFERENCES inventory_reason (id) ON DELETE RESTRICT');
        $this->addSql('ALTER TABLE inventory_movement ADD CONSTRAINT FK_40972F66A76ED395 FOREIGN KEY (user_id) REFERENCES app_user (id) ON DELETE RESTRICT');
        $this->addSql('ALTER TABLE inventory_movement ADD CONSTRAINT FK_40972F6656DA6AEE FOREIGN KEY (paca_unit_id) REFERENCES paca_unit (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE inventory_snapshot ADD CONSTRAINT FK_9807AFA4979B1AD6 FOREIGN KEY (company_id) REFERENCES company (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE inventory_snapshot ADD CONSTRAINT FK_9807AFA45080ECDE FOREIGN KEY (warehouse_id) REFERENCES warehouse (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE paca ADD CONSTRAINT FK_770BB73D44F5D008 FOREIGN KEY (brand_id) REFERENCES brand (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE paca ADD CONSTRAINT FK_770BB73D33B92F39 FOREIGN KEY (label_id) REFERENCES label_catalog (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE paca ADD CONSTRAINT FK_770BB73DEA7929DC FOREIGN KEY (quality_grade_id) REFERENCES quality_grade (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE paca ADD CONSTRAINT FK_770BB73D4EC001D1 FOREIGN KEY (season_id) REFERENCES season_catalog (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE paca ADD CONSTRAINT FK_770BB73D708A0E0 FOREIGN KEY (gender_id) REFERENCES gender_catalog (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE paca ADD CONSTRAINT FK_770BB73DE4AFAD8F FOREIGN KEY (garment_type_id) REFERENCES garment_type (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE paca ADD CONSTRAINT FK_770BB73D88DC877A FOREIGN KEY (fabric_type_id) REFERENCES fabric_type (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE paca ADD CONSTRAINT FK_770BB73D161591CD FOREIGN KEY (size_profile_id) REFERENCES size_profile (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE paca ADD CONSTRAINT FK_770BB73D2ADD6D8C FOREIGN KEY (supplier_id) REFERENCES supplier (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE paca_import_log ADD CONSTRAINT FK_D30DA832A76ED395 FOREIGN KEY (user_id) REFERENCES app_user (id)');
        $this->addSql('ALTER TABLE paca_unit ADD CONSTRAINT FK_34A1768C76A45273 FOREIGN KEY (paca_id) REFERENCES paca (id) ON DELETE RESTRICT');
        $this->addSql('ALTER TABLE paca_unit ADD CONSTRAINT FK_34A1768C5080ECDE FOREIGN KEY (warehouse_id) REFERENCES warehouse (id)');
        $this->addSql('ALTER TABLE paca_unit ADD CONSTRAINT FK_34A1768CC77159AD FOREIGN KEY (warehouse_bin_id) REFERENCES warehouse_bin (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE paca_unit ADD CONSTRAINT FK_34A1768CC023F51C FOREIGN KEY (sales_order_id) REFERENCES sales_order (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE paca_unit ADD CONSTRAINT FK_34A1768C21338DA6 FOREIGN KEY (sales_order_item_id) REFERENCES sales_order_item (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE paca_unit ADD CONSTRAINT FK_34A1768CA45D7E6A FOREIGN KEY (purchase_order_id) REFERENCES purchase_order (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE payment ADD CONSTRAINT FK_6D28840D4A7E4868 FOREIGN KEY (sale_id) REFERENCES sale (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE product ADD CONSTRAINT FK_D34A04AD12469DE2 FOREIGN KEY (category_id) REFERENCES category (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE purchase_order ADD CONSTRAINT FK_21E210B2979B1AD6 FOREIGN KEY (company_id) REFERENCES company (id) ON DELETE RESTRICT');
        $this->addSql('ALTER TABLE purchase_order ADD CONSTRAINT FK_21E210B22ADD6D8C FOREIGN KEY (supplier_id) REFERENCES supplier (id) ON DELETE RESTRICT');
        $this->addSql('ALTER TABLE purchase_order ADD CONSTRAINT FK_21E210B2A76ED395 FOREIGN KEY (user_id) REFERENCES app_user (id) ON DELETE RESTRICT');
        $this->addSql('ALTER TABLE purchase_order_item ADD CONSTRAINT FK_5ED948C3A45D7E6A FOREIGN KEY (purchase_order_id) REFERENCES purchase_order (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE purchase_order_item ADD CONSTRAINT FK_5ED948C333B92F39 FOREIGN KEY (label_id) REFERENCES label_catalog (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE purchase_order_item ADD CONSTRAINT FK_5ED948C376A45273 FOREIGN KEY (paca_id) REFERENCES paca (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE sale ADD CONSTRAINT FK_E54BC0059395C3F3 FOREIGN KEY (customer_id) REFERENCES customer (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE sale_item ADD CONSTRAINT FK_A35551FB4A7E4868 FOREIGN KEY (sale_id) REFERENCES sale (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE sale_item ADD CONSTRAINT FK_A35551FB4584665A FOREIGN KEY (product_id) REFERENCES product (id) ON DELETE RESTRICT');
        $this->addSql('ALTER TABLE sales_order ADD CONSTRAINT FK_36D222E979B1AD6 FOREIGN KEY (company_id) REFERENCES company (id) ON DELETE RESTRICT');
        $this->addSql('ALTER TABLE sales_order ADD CONSTRAINT FK_36D222EDCD6CC49 FOREIGN KEY (branch_id) REFERENCES branch (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE sales_order ADD CONSTRAINT FK_36D222E9395C3F3 FOREIGN KEY (customer_id) REFERENCES customer (id) ON DELETE RESTRICT');
        $this->addSql('ALTER TABLE sales_order ADD CONSTRAINT FK_36D222E8DE820D9 FOREIGN KEY (seller_id) REFERENCES app_user (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE sales_order ADD CONSTRAINT FK_36D222EA76ED395 FOREIGN KEY (user_id) REFERENCES app_user (id) ON DELETE RESTRICT');
        $this->addSql('ALTER TABLE sales_order_item ADD CONSTRAINT FK_5DD6A865C023F51C FOREIGN KEY (sales_order_id) REFERENCES sales_order (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE sales_order_item ADD CONSTRAINT FK_5DD6A86576A45273 FOREIGN KEY (paca_id) REFERENCES paca (id) ON DELETE RESTRICT');
        $this->addSql('ALTER TABLE sales_order_status_history ADD CONSTRAINT FK_84EEA80FC023F51C FOREIGN KEY (sales_order_id) REFERENCES sales_order (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE sales_order_status_history ADD CONSTRAINT FK_84EEA80FA76ED395 FOREIGN KEY (user_id) REFERENCES app_user (id) ON DELETE RESTRICT');
        $this->addSql('ALTER TABLE shipment_order ADD CONSTRAINT FK_79E4313DC023F51C FOREIGN KEY (sales_order_id) REFERENCES sales_order (id) ON DELETE RESTRICT');
        $this->addSql('ALTER TABLE shipment_order ADD CONSTRAINT FK_79E4313D5080ECDE FOREIGN KEY (warehouse_id) REFERENCES warehouse (id) ON DELETE RESTRICT');
        $this->addSql('ALTER TABLE shipment_order ADD CONSTRAINT FK_79E4313DB03A8386 FOREIGN KEY (created_by_id) REFERENCES app_user (id) ON DELETE RESTRICT');
        $this->addSql('ALTER TABLE shipment_order_item ADD CONSTRAINT FK_30E0C352BC89259 FOREIGN KEY (shipment_order_id) REFERENCES shipment_order (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE shipment_order_item ADD CONSTRAINT FK_30E0C3556DA6AEE FOREIGN KEY (paca_unit_id) REFERENCES paca_unit (id) ON DELETE RESTRICT');
        $this->addSql('ALTER TABLE shipment_order_item ADD CONSTRAINT FK_30E0C35EBBC642F FOREIGN KEY (scanned_by_id) REFERENCES app_user (id) ON DELETE RESTRICT');
        $this->addSql('ALTER TABLE supplier_label ADD CONSTRAINT FK_D7BC52C22ADD6D8C FOREIGN KEY (supplier_id) REFERENCES supplier (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE supplier_label ADD CONSTRAINT FK_D7BC52C21EDAAF39 FOREIGN KEY (label_catalog_id) REFERENCES label_catalog (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE supplier_brand ADD CONSTRAINT FK_C549FB722ADD6D8C FOREIGN KEY (supplier_id) REFERENCES supplier (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE supplier_brand ADD CONSTRAINT FK_C549FB7244F5D008 FOREIGN KEY (brand_id) REFERENCES brand (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE warehouse ADD CONSTRAINT FK_ECB38BFC979B1AD6 FOREIGN KEY (company_id) REFERENCES company (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE warehouse ADD CONSTRAINT FK_ECB38BFCE2AB99E6 FOREIGN KEY (warehouse_type_id) REFERENCES warehouse_type (id)');
        $this->addSql('ALTER TABLE warehouse_bin ADD CONSTRAINT FK_A0C84D415080ECDE FOREIGN KEY (warehouse_id) REFERENCES warehouse (id) ON DELETE CASCADE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE app_functionality DROP FOREIGN KEY FK_624162E87ADEAA4');
        $this->addSql('ALTER TABLE app_role_action_permission DROP FOREIGN KEY FK_EE188C05D60322AC');
        $this->addSql('ALTER TABLE app_role_action_permission DROP FOREIGN KEY FK_EE188C053EE1AEBD');
        $this->addSql('ALTER TABLE app_role_action_permission DROP FOREIGN KEY FK_EE188C059D32F035');
        $this->addSql('ALTER TABLE app_role_module_permission DROP FOREIGN KEY FK_185FCD52D60322AC');
        $this->addSql('ALTER TABLE app_role_module_permission DROP FOREIGN KEY FK_185FCD527ADEAA4');
        $this->addSql('ALTER TABLE app_user DROP FOREIGN KEY FK_88BDF3E9D60322AC');
        $this->addSql('ALTER TABLE app_user DROP FOREIGN KEY FK_88BDF3E9979B1AD6');
        $this->addSql('ALTER TABLE app_user DROP FOREIGN KEY FK_88BDF3E9DCD6CC49');
        $this->addSql('ALTER TABLE app_user DROP FOREIGN KEY FK_88BDF3E9AE80F5DF');
        $this->addSql('ALTER TABLE app_user_session DROP FOREIGN KEY FK_4AC7D15FA76ED395');
        $this->addSql('ALTER TABLE branch DROP FOREIGN KEY FK_BB861B1F979B1AD6');
        $this->addSql('ALTER TABLE department DROP FOREIGN KEY FK_CD1DE18A979B1AD6');
        $this->addSql('ALTER TABLE inventory_count DROP FOREIGN KEY FK_5945EF62979B1AD6');
        $this->addSql('ALTER TABLE inventory_count DROP FOREIGN KEY FK_5945EF625080ECDE');
        $this->addSql('ALTER TABLE inventory_count DROP FOREIGN KEY FK_5945EF62A76ED395');
        $this->addSql('ALTER TABLE inventory_count_detail DROP FOREIGN KEY FK_A18FB9AF242801B');
        $this->addSql('ALTER TABLE inventory_count_detail DROP FOREIGN KEY FK_A18FB9A76A45273');
        $this->addSql('ALTER TABLE inventory_movement DROP FOREIGN KEY FK_40972F66979B1AD6');
        $this->addSql('ALTER TABLE inventory_movement DROP FOREIGN KEY FK_40972F6676A45273');
        $this->addSql('ALTER TABLE inventory_movement DROP FOREIGN KEY FK_40972F665080ECDE');
        $this->addSql('ALTER TABLE inventory_movement DROP FOREIGN KEY FK_40972F66C77159AD');
        $this->addSql('ALTER TABLE inventory_movement DROP FOREIGN KEY FK_40972F6659BB1592');
        $this->addSql('ALTER TABLE inventory_movement DROP FOREIGN KEY FK_40972F66A76ED395');
        $this->addSql('ALTER TABLE inventory_movement DROP FOREIGN KEY FK_40972F6656DA6AEE');
        $this->addSql('ALTER TABLE inventory_snapshot DROP FOREIGN KEY FK_9807AFA4979B1AD6');
        $this->addSql('ALTER TABLE inventory_snapshot DROP FOREIGN KEY FK_9807AFA45080ECDE');
        $this->addSql('ALTER TABLE paca DROP FOREIGN KEY FK_770BB73D44F5D008');
        $this->addSql('ALTER TABLE paca DROP FOREIGN KEY FK_770BB73D33B92F39');
        $this->addSql('ALTER TABLE paca DROP FOREIGN KEY FK_770BB73DEA7929DC');
        $this->addSql('ALTER TABLE paca DROP FOREIGN KEY FK_770BB73D4EC001D1');
        $this->addSql('ALTER TABLE paca DROP FOREIGN KEY FK_770BB73D708A0E0');
        $this->addSql('ALTER TABLE paca DROP FOREIGN KEY FK_770BB73DE4AFAD8F');
        $this->addSql('ALTER TABLE paca DROP FOREIGN KEY FK_770BB73D88DC877A');
        $this->addSql('ALTER TABLE paca DROP FOREIGN KEY FK_770BB73D161591CD');
        $this->addSql('ALTER TABLE paca DROP FOREIGN KEY FK_770BB73D2ADD6D8C');
        $this->addSql('ALTER TABLE paca_import_log DROP FOREIGN KEY FK_D30DA832A76ED395');
        $this->addSql('ALTER TABLE paca_unit DROP FOREIGN KEY FK_34A1768C76A45273');
        $this->addSql('ALTER TABLE paca_unit DROP FOREIGN KEY FK_34A1768C5080ECDE');
        $this->addSql('ALTER TABLE paca_unit DROP FOREIGN KEY FK_34A1768CC77159AD');
        $this->addSql('ALTER TABLE paca_unit DROP FOREIGN KEY FK_34A1768CC023F51C');
        $this->addSql('ALTER TABLE paca_unit DROP FOREIGN KEY FK_34A1768C21338DA6');
        $this->addSql('ALTER TABLE paca_unit DROP FOREIGN KEY FK_34A1768CA45D7E6A');
        $this->addSql('ALTER TABLE payment DROP FOREIGN KEY FK_6D28840D4A7E4868');
        $this->addSql('ALTER TABLE product DROP FOREIGN KEY FK_D34A04AD12469DE2');
        $this->addSql('ALTER TABLE purchase_order DROP FOREIGN KEY FK_21E210B2979B1AD6');
        $this->addSql('ALTER TABLE purchase_order DROP FOREIGN KEY FK_21E210B22ADD6D8C');
        $this->addSql('ALTER TABLE purchase_order DROP FOREIGN KEY FK_21E210B2A76ED395');
        $this->addSql('ALTER TABLE purchase_order_item DROP FOREIGN KEY FK_5ED948C3A45D7E6A');
        $this->addSql('ALTER TABLE purchase_order_item DROP FOREIGN KEY FK_5ED948C333B92F39');
        $this->addSql('ALTER TABLE purchase_order_item DROP FOREIGN KEY FK_5ED948C376A45273');
        $this->addSql('ALTER TABLE sale DROP FOREIGN KEY FK_E54BC0059395C3F3');
        $this->addSql('ALTER TABLE sale_item DROP FOREIGN KEY FK_A35551FB4A7E4868');
        $this->addSql('ALTER TABLE sale_item DROP FOREIGN KEY FK_A35551FB4584665A');
        $this->addSql('ALTER TABLE sales_order DROP FOREIGN KEY FK_36D222E979B1AD6');
        $this->addSql('ALTER TABLE sales_order DROP FOREIGN KEY FK_36D222EDCD6CC49');
        $this->addSql('ALTER TABLE sales_order DROP FOREIGN KEY FK_36D222E9395C3F3');
        $this->addSql('ALTER TABLE sales_order DROP FOREIGN KEY FK_36D222E8DE820D9');
        $this->addSql('ALTER TABLE sales_order DROP FOREIGN KEY FK_36D222EA76ED395');
        $this->addSql('ALTER TABLE sales_order_item DROP FOREIGN KEY FK_5DD6A865C023F51C');
        $this->addSql('ALTER TABLE sales_order_item DROP FOREIGN KEY FK_5DD6A86576A45273');
        $this->addSql('ALTER TABLE sales_order_status_history DROP FOREIGN KEY FK_84EEA80FC023F51C');
        $this->addSql('ALTER TABLE sales_order_status_history DROP FOREIGN KEY FK_84EEA80FA76ED395');
        $this->addSql('ALTER TABLE shipment_order DROP FOREIGN KEY FK_79E4313DC023F51C');
        $this->addSql('ALTER TABLE shipment_order DROP FOREIGN KEY FK_79E4313D5080ECDE');
        $this->addSql('ALTER TABLE shipment_order DROP FOREIGN KEY FK_79E4313DB03A8386');
        $this->addSql('ALTER TABLE shipment_order_item DROP FOREIGN KEY FK_30E0C352BC89259');
        $this->addSql('ALTER TABLE shipment_order_item DROP FOREIGN KEY FK_30E0C3556DA6AEE');
        $this->addSql('ALTER TABLE shipment_order_item DROP FOREIGN KEY FK_30E0C35EBBC642F');
        $this->addSql('ALTER TABLE supplier_label DROP FOREIGN KEY FK_D7BC52C22ADD6D8C');
        $this->addSql('ALTER TABLE supplier_label DROP FOREIGN KEY FK_D7BC52C21EDAAF39');
        $this->addSql('ALTER TABLE supplier_brand DROP FOREIGN KEY FK_C549FB722ADD6D8C');
        $this->addSql('ALTER TABLE supplier_brand DROP FOREIGN KEY FK_C549FB7244F5D008');
        $this->addSql('ALTER TABLE warehouse DROP FOREIGN KEY FK_ECB38BFC979B1AD6');
        $this->addSql('ALTER TABLE warehouse DROP FOREIGN KEY FK_ECB38BFCE2AB99E6');
        $this->addSql('ALTER TABLE warehouse_bin DROP FOREIGN KEY FK_A0C84D415080ECDE');
        $this->addSql('DROP TABLE app_action_catalog');
        $this->addSql('DROP TABLE app_functionality');
        $this->addSql('DROP TABLE app_module');
        $this->addSql('DROP TABLE app_role');
        $this->addSql('DROP TABLE app_role_action_permission');
        $this->addSql('DROP TABLE app_role_module_permission');
        $this->addSql('DROP TABLE app_user');
        $this->addSql('DROP TABLE app_user_session');
        $this->addSql('DROP TABLE branch');
        $this->addSql('DROP TABLE brand');
        $this->addSql('DROP TABLE category');
        $this->addSql('DROP TABLE company');
        $this->addSql('DROP TABLE customer');
        $this->addSql('DROP TABLE department');
        $this->addSql('DROP TABLE fabric_type');
        $this->addSql('DROP TABLE garment_type');
        $this->addSql('DROP TABLE gender_catalog');
        $this->addSql('DROP TABLE inventory_count');
        $this->addSql('DROP TABLE inventory_count_detail');
        $this->addSql('DROP TABLE inventory_movement');
        $this->addSql('DROP TABLE inventory_reason');
        $this->addSql('DROP TABLE inventory_snapshot');
        $this->addSql('DROP TABLE label_catalog');
        $this->addSql('DROP TABLE paca');
        $this->addSql('DROP TABLE paca_import_log');
        $this->addSql('DROP TABLE paca_unit');
        $this->addSql('DROP TABLE payment');
        $this->addSql('DROP TABLE product');
        $this->addSql('DROP TABLE purchase_order');
        $this->addSql('DROP TABLE purchase_order_item');
        $this->addSql('DROP TABLE quality_grade');
        $this->addSql('DROP TABLE sale');
        $this->addSql('DROP TABLE sale_item');
        $this->addSql('DROP TABLE sales_order');
        $this->addSql('DROP TABLE sales_order_item');
        $this->addSql('DROP TABLE sales_order_status_history');
        $this->addSql('DROP TABLE season_catalog');
        $this->addSql('DROP TABLE shipment_order');
        $this->addSql('DROP TABLE shipment_order_item');
        $this->addSql('DROP TABLE size_profile');
        $this->addSql('DROP TABLE supplier');
        $this->addSql('DROP TABLE supplier_label');
        $this->addSql('DROP TABLE supplier_brand');
        $this->addSql('DROP TABLE tag');
        $this->addSql('DROP TABLE warehouse');
        $this->addSql('DROP TABLE warehouse_bin');
        $this->addSql('DROP TABLE warehouse_type');
    }
}
